version = 1

[[annotations]]
path = ["src/**/*.rs", "tests/**/*.rs", "benches/**/*.rs", "examples/**/*.rs"]
precedence = "override"
SPDX-FileCopyrightText = "2025-2026 Carlson Büth <code@cbueth.de>"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ["src/**/*.wgsl", "*.md"]
precedence = "override"
SPDX-FileCopyrightText = "2025-2026 Carlson Büth <code@cbueth.de>"
SPDX-License-Identifier = "MIT OR Apache-2.0"
